name: xxx CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1.2.0
              with:
                  node-version: 12.x

            - name: Echo Hello World
              run: echo "Hello World"
